[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
opener = "0.6.1"
rodio = "0.17.1"
normpath = "1.1.1"

[dependencies.tauri]
version = "1.4.0"
features = [
    "dialog-open",
    "window-maximize",
    "window-hide",
    "window-unmaximize",
    "window-minimize",
    "window-start-dragging",
    "window-close",
    "window-unminimize",
    "window-show",
    "dialog"
]

[dependencies.winapi]
version = "0.3.9"
features = [
    "winbase",
    "windef",
    "winuser",
    "shellapi",
    "psapi",
    "handleapi"
]

[dependencies.tokio]
version = "1.29.1"
features = [
    "default",
    "rt",
    "time"
]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
